apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: vars-{{ .Chart.Name }}
  name: vars-{{ .Chart.Name }}
data:
  MYSQL_DATABASE: my_wiki
  MYSQL_USER: wikiuser
  MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  MEDIAWIKI_DATABASE_HOST: svc-mediawiki-db
